"""CandidateRule Value -- extracted from a source document by Opus.

Carries proposed rule fields, source_document_id, source_quote, and
confidence (Reference Data § Confidence tiers):

- high: official municipal source (authority_level <= 2) + exact material match
- medium: official municipal source + category-level match
- low: third-party source or ambiguous provenance

Confidence is a tracking signal only; it never gates the apply path.
INV-DATA-001: source_document_id and source_quote must be non-null/non-empty.
"""

# LLM-extracted rule payloads are dict[str, Any]; boundary guard reads fields
# via getattr, which is also typed Any -- no tighter type is available here.
# pyright: reportExplicitAny=false, reportAny=false

import uuid
from dataclasses import dataclass
from typing import Any


@dataclass(frozen=True, slots=True)
class CandidateRule:
    """A single recycling rule candidate extracted from one source document.

    Fields:
        source_document_id: UUID of the source document this candidate was
            extracted from. Application-generated by the fetcher before the
            LLM call; must be non-null (INV-DATA-001).
        source_quote: exact verbatim span from the source backing this rule.
            Must be non-empty (INV-DATA-001).
        confidence: 'high' | 'medium' | 'low' -- set by the agent.
        jurisdiction_id: proposed jurisdiction UUID (from operator input).
        material_slug: proposed material identifier (free text from Opus).
        disposition: proposed disposition value.
        accepted_status: proposed accepted_status value.
        preparation_steps: list of preparation instructions.
        exceptions: list of exception notes.
        warnings: list of warning notes.
        effective_from: ISO date string or None.
        raw_fields: full JSON dict from the LLM for any extra fields.
    """

    source_document_id: uuid.UUID
    source_quote: str
    confidence: str
    jurisdiction_id: uuid.UUID
    material_slug: str
    disposition: str
    accepted_status: str
    preparation_steps: tuple[str, ...]
    exceptions: tuple[str, ...]
    warnings: tuple[str, ...]
    effective_from: str | None = None
    raw_fields: dict[str, Any] | None = None
