/**
 * Generated OpenAPI client -- do not hand-edit.
 *
 * Wraps openapi-fetch with the typed paths from types.ts.
 * All data-fetching in this app flows through this client or
 * through the typed helpers in lib/api/index.ts.
 *
 * Re-generated by: npm run codegen:api
 */

import "server-only";
import createClient from "openapi-fetch";
import type { paths } from "./types";

const BACKEND_URL = process.env.BACKEND_URL ?? "http://localhost:8000";

export const apiClient = createClient<paths>({
  baseUrl: BACKEND_URL,
});
