/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/ask": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Ask
     * @description Answer a recycling question grounded in jurisdiction rules.
     *
     *     Returns HTTP 200 for all retrieval outcomes including refusals.
     *     Returns HTTP 400 with error='query_too_long' when query exceeds
     *     150 characters.
     */
    post: operations["ask_ask_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/pages/jurisdiction/{slug}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get Jurisdiction Page
     * @description Return the SEO jurisdiction landing page or 404 on slug miss.
     */
    get: operations["get_jurisdiction_page_pages_jurisdiction__slug__get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/pages/jurisdiction/{j_slug}/material/{m_slug}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get Material Page
     * @description Return the SEO material detail page or 404 on slug miss.
     */
    get: operations["get_material_page_pages_jurisdiction__j_slug__material__m_slug__get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/health": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Health */
    get: operations["health_health_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    /**
     * Answer
     * @description POST /ask response body per answer.md § Response.
     *
     *     HTTP 200 for all retrieval outcomes including refusals.
     */
    Answer: {
      /** Audit Record Id */
      audit_record_id: string;
      /** Citations */
      citations: components["schemas"]["CitationWire"][];
      /** Clarifying Question */
      clarifying_question: string | null;
      /** Confidence */
      confidence: string;
      /** Do Not Do */
      do_not_do: string[];
      /** Dropoff Options */
      dropoff_options: components["schemas"]["FacilityWire"][];
      jurisdiction: components["schemas"]["JurisdictionRefWire"];
      /** Preparation Steps */
      preparation_steps: string[];
      /** Recommended Action */
      recommended_action: string;
      /** Refusal Reason */
      refusal_reason: string | null;
      /** Short Answer */
      short_answer: string;
    };
    /**
     * AskRequest
     * @description POST /ask request body per answer.md § Request.
     */
    AskRequest: {
      /**
       * Query
       * @description Free-text user question, max 150 chars
       */
      query: string;
      /**
       * Location
       * @description City name, 'Denver, CO', or ZIP
       */
      location: string;
    };
    /**
     * CitationWire
     * @description A source citation in the wire response.
     *
     *     quote is optional -- omitted when no source quote is available.
     *     Per answer.md § Citation.
     */
    CitationWire: {
      /** Title */
      title: string;
      /** Url */
      url: string;
      /** Quote */
      quote?: string | null;
    };
    /**
     * ErrorEnvelope
     * @description Typed error envelope for application-level errors.
     *
     *     All non-2xx application errors use this shape:
     *       { "error": "<machine_code>" }
     *
     *     Known codes per answer.md § Known error codes:
     *       query_too_long  -- 400, POST /ask, query > 150 chars
     *       not_found       -- 404, page routes, slug miss
     *       internal_error  -- 500, all routes, unhandled server error
     */
    ErrorEnvelope: {
      /** Error */
      error: string;
    };
    /**
     * FacilityWire
     * @description A dropoff facility.
     *
     *     Always [] in Step 2. Shape defined so consumers can type the
     *     field ahead of Step 3.
     */
    FacilityWire: {
      /** Id */
      id: string;
      /** Name */
      name: string;
      /** Address */
      address: string;
    };
    /** HTTPValidationError */
    HTTPValidationError: {
      /** Detail */
      detail?: components["schemas"]["ValidationError"][];
    };
    /**
     * JurisdictionPageWire
     * @description Response body for GET /pages/jurisdiction/{slug}.
     */
    JurisdictionPageWire: {
      jurisdiction: components["schemas"]["JurisdictionWire"];
      /** Materials */
      materials: components["schemas"]["MaterialSummaryWire"][];
    };
    /**
     * JurisdictionRefWire
     * @description A resolved jurisdiction reference. id is always a non-empty UUID.
     */
    JurisdictionRefWire: {
      /** Id */
      id: string | null;
      /** Name */
      name: string;
    };
    /**
     * JurisdictionWire
     * @description Jurisdiction shape for SEO pages.
     *
     *     Richer than JurisdictionRefWire from answer.md: includes slug for
     *     in-page link construction.
     */
    JurisdictionWire: {
      /** Id */
      id: string;
      /** Name */
      name: string;
      /** Slug */
      slug: string;
    };
    /**
     * MaterialDetailWire
     * @description Material identity block for the material page.
     */
    MaterialDetailWire: {
      /** Id */
      id: string;
      /** Slug */
      slug: string;
      /** Canonical Name */
      canonical_name: string;
    };
    /**
     * MaterialPageWire
     * @description Response body for GET /pages/jurisdiction/{j}/material/{m}.
     */
    MaterialPageWire: {
      jurisdiction: components["schemas"]["JurisdictionWire"];
      material: components["schemas"]["MaterialDetailWire"];
      rule: components["schemas"]["RuleWire"];
      /** Citations */
      citations: components["schemas"]["CitationWire"][];
    };
    /**
     * MaterialSummaryWire
     * @description List element in JurisdictionPage.materials.
     */
    MaterialSummaryWire: {
      /** Id */
      id: string;
      /** Slug */
      slug: string;
      /** Canonical Name */
      canonical_name: string;
      /** Accepted Status */
      accepted_status: string;
      /** Needs Preparation */
      needs_preparation: boolean;
      citation: components["schemas"]["CitationWire"];
    };
    /**
     * RuleWire
     * @description Rule block for the material page.
     *
     *     Shaped to the page's use case, not to the full rules row.
     */
    RuleWire: {
      /** Disposition */
      disposition: string;
      /** Accepted Status */
      accepted_status: string;
      /** Preparation Steps */
      preparation_steps: string[];
      /** Exceptions */
      exceptions: string[];
      /** Warnings */
      warnings: string[];
    };
    /** ValidationError */
    ValidationError: {
      /** Location */
      loc: (string | number)[];
      /** Message */
      msg: string;
      /** Error Type */
      type: string;
      /** Input */
      input?: unknown;
      /** Context */
      ctx?: Record<string, never>;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  ask_ask_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["AskRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Answer"];
        };
      };
      /** @description query_too_long -- query exceeds 150 characters */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorEnvelope"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  get_jurisdiction_page_pages_jurisdiction__slug__get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        slug: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["JurisdictionPageWire"];
        };
      };
      /** @description not_found -- no jurisdiction for this slug */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorEnvelope"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  get_material_page_pages_jurisdiction__j_slug__material__m_slug__get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        j_slug: string;
        m_slug: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["MaterialPageWire"];
        };
      };
      /** @description not_found -- no jurisdiction or material for these slugs */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorEnvelope"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  health_health_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            [key: string]: string;
          };
        };
      };
    };
  };
}
